# default: &default
#   adapter: postgresql
#   encoding: unicode
#   host: <%= ENV['DB_HOST'] %>
#   port: <%= ENV['DB_PORT'] %>
#   username: <%= ENV['DB_USER'] %>
#   password: <%= ENV['DB_PASSWORD'] %>
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   database: <%= ENV['DB_NAME'] %>

# test:
#   <<: *default
#   database: <%= ENV['DB_NAME'] %>_test

# production:
#   <<: *default
#   database: <%= ENV['DB_NAME'] %>_production
# # default: &default
# #   adapter: postgresql
# #   encoding: unicode
# #   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# # development:
# #   <<: *default
# #   url: <%= ENV['DATABASE_URL'] %>
# #   database: my_marketplace_apis_development

# # test:
# #   <<: *default
# #   database: marketplace_client_test

# # production:
# #   <<: *default
# #   url: <%= ENV['DATABASE_URL'] %>
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] %>

test:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_production
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
